//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buiness
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string ArrivTime { get; set; }
        public int Order { get; set; }
        public int DistributionFee { get; set; }
    }
}
